version: '3'
services:
  
    
  frontend:
    image: swaggerapi/swagger-ui:latest
    container_name: aos2023_ui
    ports:
      - "8000:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yaml
    volumes:
      - ./openapi:/aos:ro
    depends_on:
    -  app
    networks:
      - mynetwork
    

  bd:
    image: mysql:8.0.33
    container_name: BaseDeDatos
    restart: always
    ports:
      - "3307:3306"
    
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aos
      MYSQL_ROOT_HOST: '%'
     
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  app:
    command: bash -c "while ! nc -z bd 3306; do sleep 1; done && python app.py"
    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/app

    depends_on:
      - bd
    networks:
      - mynetwork
    
      

volumes:
  mysql-data:
  
networks:
  mynetwork:
    driver: bridge
    