version: "3"
name: mock_api
services:
  mock_backend:
    image: stoplight/prism:4
    container_name: aos2023_mock
    command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
    ports:
      - "4010:4010"
    volumes:
      - ./openapi:/aos:ro

  frontend_swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: aos2023_ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /aos/openapi.yaml
    volumes:
      - ./openapi:/aos:ro

  proxy:
    image: caddy:latest
    container_name: aos2023_proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
    ports:
      - "80:80"
    depends_on:
      - mock_backend
