apiVersion: v1
kind: Service
metadata:
  name: ui-facturas
spec:
  selector:
    app: ui-facturas
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30089
  type: LoadBalancer
  